version: '3.8'
services:
  pgtest:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    ports:
      - "55432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 20
    volumes:
      - pgtest-data:/var/lib/postgresql/data
volumes:
  pgtest-data:

