version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15.4-alpine
    container_name: bi-platform-postgres
    environment:
      POSTGRES_DB: bi_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bi-platform-network

  # Redis Cache
  redis:
    image: redis:7.2.1-alpine
    container_name: bi-platform-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - bi-platform-network

  # MySQL Database (for multi-database connectivity testing)
  mysql:
    image: mysql:8.0
    container_name: bi-platform-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-prootpassword']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bi-platform-network

  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: bi-platform-sqlserver
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: YourStrong!Passw0rd
      MSSQL_PID: Developer
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-scripts/sqlserver:/docker-entrypoint-initdb.d
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'SELECT 1' || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - bi-platform-network

  # MongoDB Database
  mongodb:
    image: mongo:6.0
    container_name: bi-platform-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: test_db
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts/mongodb:/docker-entrypoint-initdb.d
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bi-platform-network

  # Cassandra Database
  cassandra:
    image: cassandra:4.1
    container_name: bi-platform-cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: bi-platform-cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
    ports:
      - '9042:9042'
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init-scripts/cassandra:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'cqlsh -e "describe cluster"']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - bi-platform-network

  # ClickHouse Database
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: bi-platform-clickhouse
    environment:
      CLICKHOUSE_DB: test_db
      CLICKHOUSE_USER: testuser
      CLICKHOUSE_PASSWORD: testpassword
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - '8123:8123'  # HTTP interface
      - '9000:9000'  # Native client
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./init-scripts/clickhouse:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:8123/ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bi-platform-network

  # Oracle Database XE
  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: bi-platform-oracle
    environment:
      ORACLE_PASSWORD: OraclePassword123
      ORACLE_DATABASE: TESTDB
      APP_USER: testuser
      APP_USER_PASSWORD: testpassword
    ports:
      - '1521:1521'
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init-scripts/oracle:/container-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'healthcheck.sh']
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - bi-platform-network

  # Keycloak Authentication
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: bi-platform-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: true
    command: start-dev
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - bi-platform-network

  # Backend API
  api:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.api
    container_name: bi-platform-api
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://postgres:password@postgres:5432/bi_platform
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      KEYCLOAK_URL: http://keycloak:8080/auth
      KEYCLOAK_REALM: bi-platform
      KEYCLOAK_CLIENT_ID: api-service
      TENANT_ID: default
      LOG_LEVEL: debug
      CORS_ORIGIN: http://localhost:3000
    ports:
      - '3001:3001'
    volumes:
      - ../../apps/api/src:/app/apps/api/src
      - ../../logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - bi-platform-network

  # Frontend Web
  web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.web
    container_name: bi-platform-web
    environment:
      VITE_API_URL: http://localhost:8000/api/v1
    ports:
      - '3000:80'
    depends_on:
      - api
    networks:
      - bi-platform-network

  # Kong API Gateway
  kong-database:
    image: postgres:15.4-alpine
    container_name: bi-platform-kong-db
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U kong']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bi-platform-network

  kong-migration:
    image: kong:3.4.0-alpine
    container_name: bi-platform-kong-migration
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    depends_on:
      kong-database:
        condition: service_healthy
    networks:
      - bi-platform-network

  kong:
    image: kong:3.4.0-alpine
    container_name: bi-platform-kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - '8000:8000'  # Proxy
      - '8443:8443'  # Proxy SSL
      - '8001:8001'  # Admin API
      - '8002:8002'  # Admin GUI
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_completed_successfully
    healthcheck:
      test: ['CMD', 'kong', 'health']
      interval: 10s
      timeout: 10s
      retries: 10
    networks:
      - bi-platform-network

volumes:
  postgres_data:
  redis_data:
  mysql_data:
  sqlserver_data:
  mongodb_data:
  cassandra_data:
  clickhouse_data:
  oracle_data:
  kong_data:

networks:
  bi-platform-network:
    driver: bridge

